### ISSUE TITLE
[0.9.0] FIXME in HTTP headers and console clients

### ISSUE THREAD

**Issue by fromYukki** [influxdb/influxdb#2958]
Hello
I noticed that then I run the console client I see.
```
# ./influx
Connected to http://localhost:8086 version FIXME
```
The same situation with headers in response on API request
```
HTTP/1.1 204 No Content
Request-Id: 5c4cb423-10f1-11e5-828d-000000000000
X-Influxdb-Version: FIXME
Date: Fri, 12 Jun 2015 10:54:12 GMT
```

**Comment by otoolep** [comment]
Thanks for the report @fromYukki -- this has been fixed by https://github.com/influxdb/influxdb/pull/2928.

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/pull/2969 will actually fix this issue.

**Comment by otoolep** [comment]
All fixed.

**Comment by jjfazio** [comment]
I have just installed the latest version of influxdb (version 0.9.0) and I am still seeing this issue. Installed influxdb using homebrew on Mac OSX. 
Console output:
```    
influx
Connected to http://localhost:8086 version FIXME
InfluxDB shell 0.9.0
```

**Comment by otoolep** [comment]
@jjfazio -- 0.9.1 is actually the latest version, and this issue has been fixed in that release. You can find it here:

https://influxdb.com/download/index.html

**Comment by jjfazio** [comment]
Thanks, that did the trick.
